#define SCREEN_WIDTH  320
#define SCREEN_HEIGHT 320
#define BOARD_SIZE 320

#define BOARD_MARGIN (SCREEN_WIDTH - BOARD_SIZE) / 2
#define SQUARE_SIZE ( BOARD_SIZE / 8)
#define HISTORY_WIDTH 60
#define INPUT_HEIGHT 60

